version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=value
      - NEXTAUTH_SECRET=value
      - NEXTAUTH_URL=value
      - DISCORD_CLIENT_ID=aa
      - DISCORD_CLIENT_SECRET=aa
      - GOOGLE_CLIENT_ID=value
      - GOOGLE_CLIENT_SECRET=value