import { siteConfig } from "./site";

export const cardsConfig = {
    pro: {
        title: "PRO Plan",
        badgeText: "BEST DEAL",
        description: "For serious office workers",
        bulletPoints: ["Superfast!", "For hardworking workers only!", "Mega ez!"],
        priceTag: siteConfig.price.subscriptions.pro,
        imgUrl: "/static/images/business-people.jpg",
        priceDescription: undefined,
        purchaseTier: undefined,
        purchaseBtnDescription: undefined,
    },
    conference: {
        title: "+Conference Plan",
        badgeText: undefined,
        description: "For serious office workers",
        bulletPoints: ["Superfast!", "For hardworking workers only!", "Mega ez!"],
        priceTag: siteConfig.price.subscriptions.plusConference,
        imgUrl: "/static/images/conference-room.jpg",
        priceDescription: undefined,
        purchaseTier: undefined,
        purchaseBtnDescription: undefined,
    },
    phone: {
        title: "+Phone Plan",
        badgeText: undefined,
        description: "For serious office workers",
        bulletPoints: ["Superfast!", "For hardworking workers only!", "Mega ez!"],
        priceTag: siteConfig.price.subscriptions.plusPhone,
        imgUrl: "/static/images/conference-room.jpg",
        priceDescription: undefined,
        purchaseTier: undefined,
        purchaseBtnDescription: undefined,
    },
    basic: {
        title: "Basic Plan",
        badgeText: undefined,
        description: "For serious office workers",
        bulletPoints: ["Superfast!", "Mega ez!"],
        priceTag: siteConfig.price.subscriptions.basic,
        imgUrl: "/static/images/conference-room.jpg",
        priceDescription: undefined,
        purchaseTier: undefined,
        purchaseBtnDescription: undefined,
    },
    flexpay: {
        title: "FlexPay Plan",
        badgeText: undefined,
        description: "Most flexible workers",
        bulletPoints: ["Purchase only what you need!", "Mega ez!"],
        priceTag: siteConfig.price.subscriptions.flexPay,
        imgUrl: "/static/images/conference-room.jpg",
        priceDescription: "Individual purchases",
        purchaseTier: undefined,
        purchaseBtnDescription: "Sign Up",
    },
}