import Head from "next/head";
import { type NextPageWithLayout } from "./_app";
import { type ReactElement } from 'react';
import { Alert } from "~/components/Alert";
import RootLayout from "~/components/RootLayout";
import { type GetServerSidePropsContext } from "next";
import { getServerAuthSession } from "~/server/auth";


export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  // Prefetches the auth session to avoid janky login UI
  const session = await getServerAuthSession(ctx);

  return {
    props: { session },
  };
}

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Rokni Office</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="spacer layer1">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-32">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            The <span className="text-sky-200">Rokni Office</span> App
          </h1>
        </div>
      </div>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
        <Alert text={"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}/>
                            
      </div>


      
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <RootLayout>
      {page}
    </RootLayout>
  );
};

export default Home;
